
package practico5.Vistas;

import clasesEstaticas.Gestion;
import java.awt.event.KeyEvent;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import practico5.Entidades.Contacto;

/**
 *
 * @author Cetera Evelyn
 */
public class VistaBorrarContacto extends javax.swing.JInternalFrame {


            
    public VistaBorrarContacto() {
        initComponents();
        llenarListaDNI();
    }
    
    private void llenarListaDNI(){
       DefaultListModel<Long> modelo = new DefaultListModel<>();
        Set<Long> dni = Gestion.listarDni();
        for(Long d : dni){
            modelo.addElement(d);
        }
        jListDNI.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDNI = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableContacto = new javax.swing.JTable();
        jButtonBorrarContacto = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(153, 204, 255));
        jLabelTitulo.setText("Borrar Contacto");

        jLabel1.setText("DNI:");

        jTextFieldDNI.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldDNI.setMinimumSize(new java.awt.Dimension(90, 40));
        jTextFieldDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDNIKeyReleased(evt);
            }
        });

        jListDNI.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListDNIValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListDNI);

        jTableContacto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Apellido", "Nombre", "Direccion", "Ciudad", "Telefono"
            }
        ));
        jScrollPane2.setViewportView(jTableContacto);

        jButtonBorrarContacto.setText("Borrar Contacto");
        jButtonBorrarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarContactoActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jButtonBorrarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitulo)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrarContacto)
                    .addComponent(jButtonSalir))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListDNIValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListDNIValueChanged
        // TODO add your handling code here:
        
        if(evt.getValueIsAdjusting()){//con este método ignoramos eventos intermedios
            return;
        }
        Long dniSelect = jListDNI.getSelectedValue();
            if(dniSelect == null) {
                return; 
            }
        Long tel = Gestion.buscarTelefonoPorDni(dniSelect);
        Contacto c = Gestion.buscarDni(dniSelect);
        if(c == null){
            return;
        }
        
        DefaultTableModel modelTabla = (DefaultTableModel) jTableContacto.getModel();//modelo de tabla
        modelTabla.setRowCount(0);//reset
        
        
        String ciudad; 
        if(c.getCiudad() !=null){//Verificamos
            ciudad = c.getCiudad().getNombre();
        }else {
            ciudad = "Sin ciudad";
        }
        //acá llenamos la tabla 
        modelTabla.addRow(new Object[] {
            c.getDni(),
            c.getApellido(),
            c.getNombre(),
            ciudad,
            c.getDireccion(),
            tel
        });
        
    }//GEN-LAST:event_jListDNIValueChanged

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIKeyReleased
        // TODO add your handling code here:
        char c = evt.getKeyChar();//este metodo obtiene los caracteres ingresados 
        if(!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c!= KeyEvent.VK_DELETE){ //Esto acepta solo números, espacios y borrados... el resto se bloquea
            evt.consume(); 
        }
        
        String dniStr = jTextFieldDNI.getText(); 
        DefaultListModel<Long> mod = new DefaultListModel<>();
        
        if(!dniStr.isEmpty()){ 
            try{ 
                for (Long d : Gestion.listarDni()) { 
                    if(String.valueOf(d).startsWith(dniStr)){ 
                        mod.addElement(d); 
                    } 
                } 
            }catch(NumberFormatException e){ 
                JOptionPane.showMessageDialog(this,"Debe ser un valor numérico","ERROR",JOptionPane.ERROR_MESSAGE); 
            } 
        } 
        jListDNI.setModel(mod); 
    }//GEN-LAST:event_jTextFieldDNIKeyReleased

    private void jButtonBorrarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarContactoActionPerformed
        // TODO add your handling code here:
        //Falta implementar 
        
    }//GEN-LAST:event_jButtonBorrarContactoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarContacto;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList<Long> jListDNI;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableContacto;
    private javax.swing.JTextField jTextFieldDNI;
    // End of variables declaration//GEN-END:variables
}
