
package practico5;

import practico5.Vistas.VistaAgregarCiudad;
import practico5.Vistas.VistaBorrarContacto;
import practico5.Vistas.VistaBuscarTelefonoPorApellido;



/**
 *
 * @author Cetera Evelyn
 */
public class VistaDirectorioPrincipal extends javax.swing.JFrame {

    public VistaDirectorioPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuContacto = new javax.swing.JMenu();
        jMIAgregarContacto = new javax.swing.JMenuItem();
        jMenuItemBuscarContacto = new javax.swing.JMenuItem();
        jMenuItemBorrarContacto = new javax.swing.JMenuItem();
        jMenuDirectorio = new javax.swing.JMenu();
        jMILista = new javax.swing.JMenuItem();
        JMIBuscarTelPorApellido = new javax.swing.JMenuItem();
        jMenuCiudad = new javax.swing.JMenu();
        jMIAgregarCiudad = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(Escritorio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        jMenuContacto.setText("Contacto");

        jMIAgregarContacto.setText("Agregar Contacto");
        jMIAgregarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAgregarContactoActionPerformed(evt);
            }
        });
        jMenuContacto.add(jMIAgregarContacto);

        jMenuItemBuscarContacto.setText("Buscar Contacto");
        jMenuItemBuscarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarContactoActionPerformed(evt);
            }
        });
        jMenuContacto.add(jMenuItemBuscarContacto);

        jMenuItemBorrarContacto.setText("Borrar Contacto");
        jMenuItemBorrarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBorrarContactoActionPerformed(evt);
            }
        });
        jMenuContacto.add(jMenuItemBorrarContacto);

        jMenuBar1.add(jMenuContacto);

        jMenuDirectorio.setText("Directorio");

        jMILista.setText("Buscar Contactos por Ciudad");
        jMILista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListaActionPerformed(evt);
            }
        });
        jMenuDirectorio.add(jMILista);

        JMIBuscarTelPorApellido.setText("Buscar Telefono por Apellido");
        JMIBuscarTelPorApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIBuscarTelPorApellidoActionPerformed(evt);
            }
        });
        jMenuDirectorio.add(JMIBuscarTelPorApellido);

        jMenuBar1.add(jMenuDirectorio);

        jMenuCiudad.setText("Ciudad");

        jMIAgregarCiudad.setText("Agregar Ciudad");
        jMIAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAgregarCiudadActionPerformed(evt);
            }
        });
        jMenuCiudad.add(jMIAgregarCiudad);

        jMenuBar1.add(jMenuCiudad);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIAgregarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgregarContactoActionPerformed
        // TODO add your handling code here AGREGAR CONTACTO - FRAME "CONTACTO":
        Escritorio.removeAll();
        Escritorio.repaint();
        VistaAgregarContacto vac = new VistaAgregarContacto();
        vac.setVisible(true);
        Escritorio.add(vac);
        Escritorio.moveToFront(vac);
    }//GEN-LAST:event_jMIAgregarContactoActionPerformed

    private void jMIListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListaActionPerformed
        // TODO add your handling code here BUSCAR CONTACTO POR CIUDAD - FRAME "DIRECTORIO":
        Escritorio.removeAll();
        Escritorio.repaint();
        VistaBuscarContactoPorCiudad vd = new VistaBuscarContactoPorCiudad();
        vd.setVisible(true);
        Escritorio.add(vd);
        Escritorio.moveToFront(vd);
    }//GEN-LAST:event_jMIListaActionPerformed

    private void jMIAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgregarCiudadActionPerformed
        // TODO add your handling code here AGREGAR CIUDAD - MENU "CIUDAD":
        Escritorio.removeAll();
        Escritorio.repaint();
        VistaAgregarCiudad vaciudad = new VistaAgregarCiudad();
        vaciudad.setVisible(true);
        Escritorio.add(vaciudad);
        Escritorio.moveToFront(vaciudad);
    }//GEN-LAST:event_jMIAgregarCiudadActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here MENU "SALIR":
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuItemBorrarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBorrarContactoActionPerformed
        // TODO add your handling code here: BORRAR CONTACTO - MENU "CONTACTO"
        Escritorio.removeAll();
        Escritorio.repaint();
        VistaBorrarContacto vbcont = new VistaBorrarContacto();
        vbcont.setVisible(true);
        Escritorio.add(vbcont);
        Escritorio.moveToFront(vbcont);
    }//GEN-LAST:event_jMenuItemBorrarContactoActionPerformed

    private void jMenuItemBuscarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarContactoActionPerformed
        // TODO add your handling code here BUSCAR CONTACTO - MENU "CONTACTO":
        Escritorio.removeAll();
        Escritorio.repaint();
        VistaBuscarContacto vbc = new VistaBuscarContacto();
        vbc.setVisible(true);
        Escritorio.add(vbc);
        Escritorio.moveToFront(vbc);
    }//GEN-LAST:event_jMenuItemBuscarContactoActionPerformed

    private void JMIBuscarTelPorApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIBuscarTelPorApellidoActionPerformed
        // TODO add your handling code here: BUSCAR TELEFONO POR APELLIDO - MENU "DIRECTORIO":
        Escritorio.removeAll();
        Escritorio.repaint();
        VistaBuscarTelefonoPorApellido vbta = new VistaBuscarTelefonoPorApellido();
        vbta.setVisible(true);
        Escritorio.add(vbta);
        Escritorio.moveToFront(vbta);
    }//GEN-LAST:event_JMIBuscarTelPorApellidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaDirectorioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaDirectorioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaDirectorioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaDirectorioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VistaDirectorioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem JMIBuscarTelPorApellido;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMIAgregarCiudad;
    private javax.swing.JMenuItem jMIAgregarContacto;
    private javax.swing.JMenuItem jMILista;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCiudad;
    private javax.swing.JMenu jMenuContacto;
    private javax.swing.JMenu jMenuDirectorio;
    private javax.swing.JMenuItem jMenuItemBorrarContacto;
    private javax.swing.JMenuItem jMenuItemBuscarContacto;
    private javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
